name: Spam Detection

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  issues: write  # Allows the action to read and write issues comments
  pull-requests: write  # Allows the action to read and write pull request comments
  discussions: write  # Allows the action to read and write discussion comments
  contents: read  # Allows access to the repository contents

jobs:
  detect-spam:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Caches pip packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}  # Unique key based on OS and requirements file
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install packages listed in a requirements file

      - name: Run Spam Detection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/spam_detector.py
